
# Machine Learning Return Prediction + Elastic-Net Regularised Mean-Variance
# Portfolio Optimisation via Simulated Annealing -- reference implementation

Single-file, executable pipeline behind every table and figure in the
manuscript. It runs end to end on the real dataset
(`clean_sp500_stock_2018_2023.csv`, `clean_sp500_index_2018_2023.csv`) and
reproduces:

- **Tables 2-3**: prediction accuracy by train/test split and at each model's
  empirically best split
- **Table 4 / Fig. 3**: top-10 forward candidate pool per model, and their
  monthly-return trajectories
- **Table 7 (alpha calibration)**: the validation grid search that replaces
  the originally-borrowed `alpha=0.06` (Yen & Yen, 2014, a different dataset)
  with a calibrated `alpha=0.001`
- **Fig. 4**: portfolio performance vs. asset-pool size
- **Tables 5-6 / Figs. 5-6**: SA-optimised weight allocations and cumulative
  return vs. the equal-weight (1/N) benchmark, at the calibrated alpha, under
  both risk regimes ($\lambda=0.01$ return-seeking, $\lambda=0.99$
  risk-averse)

Where the manuscript's equations leave a modelling choice undocumented (e.g.
the exact feature set for the six predictors), this notebook makes an
explicit, commented choice rather than a hidden one -- see the markdown note
in each section, and `README.md` for the full list.

## Contents
1. Setup and configuration
2. Data loading and feature engineering
3. Six return-prediction models (RF, AdaBoost, XGBoost, SVR, KNN, RNN)
4. Prediction experiments -- accuracy by split, best-split summary, top-10 pools
5. Figure 3 -- candidate-pool monthly returns (small multiples, one panel per model)
6. Elastic-net mean-variance portfolio model + simulated annealing solver
7. Calibrating the regularisation strength alpha (validation grid search)
8. Portfolio experiments at the calibrated alpha -- asset-count sensitivity,
   risk-regime allocations, cumulative return vs. 1/N
9. Results summary

Run all cells top to bottom. Section 7 (the alpha grid search) is the slowest
part (~10-15 minutes on 2 cores); Section 8's risk-regime tables are the next
slowest. Expect ~30-45 minutes end to end.

## 1. Setup and configuration

In [1]:

import json
import time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from IPython.display import display

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
import torch
import torch.nn as nn

import os
os.makedirs("outputs", exist_ok=True)

RANDOM_STATE = 42
SEED = 42
np.random.seed(RANDOM_STATE)
torch.manual_seed(RANDOM_STATE)

STOCK_CSV = "clean_sp500_stock_2018_2023.csv"
INDEX_CSV = "clean_sp500_index_2018_2023.csv"
OUT = "outputs"


## 2. Data loading and feature engineering

**Documented assumption:** the manuscript states only that "monthly returns
of stocks are used as an input variable". We build a standard, defensible
lag/rolling-statistics feature set: the three preceding months' returns, a
3-month rolling mean/std of return, month-over-month volume change, and the
S&P 500 index return for that month. Target = that month's realised return.
Companies with fewer than 60 months of history (2020-2022 spin-offs/IPOs)
are dropped.

In [2]:

MIN_MONTHS = 60
FEATURE_COLS = [
    "lag1_return", "lag2_return", "lag3_return",
    "roll_mean_3", "roll_std_3",
    "volume_chg", "mkt_return",
]

def _month_index(df):
    return (df["Year"] - df["Year"].min()) * 12 + df["Month"]

def load_raw(stock_path=STOCK_CSV, index_path=INDEX_CSV):
    stock = pd.read_csv(stock_path)
    index = pd.read_csv(index_path)
    stock["t"] = _month_index(stock)
    index["t"] = _month_index(index)
    return stock, index

def build_panel(stock_path=STOCK_CSV, index_path=INDEX_CSV, min_months=MIN_MONTHS):
    stock, index = load_raw(stock_path, index_path)

    counts = stock.groupby("Company")["t"].nunique()
    keep = counts[counts >= min_months].index
    stock = stock[stock["Company"].isin(keep)].copy()
    stock = stock.sort_values(["Company", "t"]).reset_index(drop=True)

    mkt = index.set_index("t")["mo_return"].rename("mkt_return")

    frames = []
    for company, g in stock.groupby("Company", sort=False):
        g = g.sort_values("t").reset_index(drop=True)
        r = g["mo_return"]
        g["lag1_return"] = r.shift(1)
        g["lag2_return"] = r.shift(2)
        g["lag3_return"] = r.shift(3)
        g["roll_mean_3"] = r.shift(1).rolling(3).mean()
        g["roll_std_3"] = r.shift(1).rolling(3).std()
        g["volume_chg"] = g["Volume"].pct_change()
        g["target_return"] = r
        frames.append(g)

    panel = pd.concat(frames, ignore_index=True)
    panel["mkt_return"] = panel["t"].map(mkt)
    panel = panel.dropna(subset=FEATURE_COLS + ["target_return"]).reset_index(drop=True)
    return panel

def latest_feature_snapshot(panel):
    idx = panel.groupby("Company")["t"].idxmax()
    return panel.loc[idx].reset_index(drop=True)

def wide_returns(stock_path=STOCK_CSV, index_path=INDEX_CSV, min_months=MIN_MONTHS):
    stock, _ = load_raw(stock_path, index_path)
    counts = stock.groupby("Company")["t"].nunique()
    keep = counts[counts >= min_months].index
    stock = stock[stock["Company"].isin(keep)].copy()
    wide = stock.pivot_table(index="t", columns="Company", values="mo_return")
    date_map = stock.drop_duplicates("t").set_index("t")[["Year", "Month"]]
    return wide, date_map

panel = build_panel()
print(f"panel: {panel.shape[0]} samples, {panel['Company'].nunique()} companies")
display(panel[FEATURE_COLS + ["target_return"]].describe())

panel: 29946 samples, 491 companies

,lag1_return,lag2_return,lag3_return,roll_mean_3,roll_std_3,volume_chg,mkt_return,target_return
count,29946.000000,29946.000000,29946.000000,29946.000000,29946.000000,29946.000000,29946.000000,29946.000000
mean,0.012382,0.012232,0.011624,0.012079,0.082827,0.054656,0.008748,0.012100
std,0.102215,0.102188,0.102169,0.054384,0.066088,3.044830,0.052928,0.102076
min,-0.832263,-0.832263,-0.832263,-0.363999,0.000694,-0.909092,-0.125119,-0.832263
25%,-0.043440,-0.043474,-0.044512,-0.017311,0.043268,-0.185596,-0.026112,-0.043396
50%,0.012748,0.012250,0.011264,0.012268,0.070368,-0.021189,0.018388,0.011962
75%,0.065167,0.064819,0.064336,0.040882,0.106666,0.179390,0.039313,0.064780
max,4.897943,4.897943,4.897943,1.678771,3.082358,522.444312,0.126844,4.897943


## 3. Six return-prediction models

Hyperparameters follow Table 1 of the manuscript as closely as possible on
this 7-feature set. Deviations (Random Forest's `max_features: 40`, which
exceeds the number of features available here; RNN epochs reduced from 500
to 30 for tractability) are noted inline and disclosed in the manuscript's
Limitations section.

In [3]:

def make_rf():
    # Table 1: n_estimators=500, max_depth=20, min_samples_split=10,
    # min_samples_leaf=10, max_features=40 (capped to 'sqrt' since 40 > 7 features here).
    return RandomForestRegressor(
        n_estimators=500, max_depth=20, min_samples_split=10,
        min_samples_leaf=10, max_features="sqrt",
        random_state=RANDOM_STATE, n_jobs=-1,
    )

def make_adaboost():
    # Table 1: n_estimators=50, learning_rate=1.
    base = DecisionTreeRegressor(max_depth=3, random_state=RANDOM_STATE)
    try:
        return AdaBoostRegressor(estimator=base, n_estimators=50, learning_rate=1.0,
                                  random_state=RANDOM_STATE)
    except TypeError:
        return AdaBoostRegressor(base_estimator=base, n_estimators=50, learning_rate=1.0,
                                  random_state=RANDOM_STATE)

def make_xgboost():
    # Table 1: n_round=100, max_depth=7, learning_rate=0.01, gamma=2.
    return XGBRegressor(
        n_estimators=100, max_depth=7, learning_rate=0.01, gamma=2,
        random_state=RANDOM_STATE, n_jobs=-1, verbosity=0,
    )

def make_svr():
    # Table 1: C=10, gamma=0.1 (RBF kernel).
    return SVR(C=10, gamma=0.1, kernel="rbf")

def make_knn():
    # Table 1: n_neighbors=3.
    return KNeighborsRegressor(n_neighbors=3)

In [4]:

# --- RNN (PyTorch) --------------------------------------------------------
# Table 1 specifies hidden layers=4, batch_size=128, epochs=500. The three lag
# returns are treated as a length-3 sequence fed to the recurrent unit, with
# the remaining engineered features concatenated to the final hidden state
# before the output layer. Epochs are capped at 30 (not 500) purely for
# tractability in this environment -- a documented deviation.
SEQ_FEATURES = ["lag3_return", "lag2_return", "lag1_return"]
AUX_FEATURES = ["roll_mean_3", "roll_std_3", "volume_chg", "mkt_return"]
RNN_EPOCHS = 30
RNN_BATCH = 128
RNN_HIDDEN = 16
RNN_LAYERS = 4

class ReturnRNN(nn.Module):
    def __init__(self, n_aux, hidden=RNN_HIDDEN, layers=RNN_LAYERS):
        super().__init__()
        self.rnn = nn.RNN(input_size=1, hidden_size=hidden, num_layers=layers,
                           batch_first=True, nonlinearity="tanh")
        self.head = nn.Sequential(
            nn.Linear(hidden + n_aux, 16), nn.ReLU(), nn.Linear(16, 1)
        )

    def forward(self, seq, aux):
        out, hN = self.rnn(seq)
        last = out[:, -1, :]
        x = torch.cat([last, aux], dim=1)
        return self.head(x).squeeze(-1)

class RNNRegressor:
    def __init__(self, epochs=RNN_EPOCHS, batch_size=RNN_BATCH, lr=1e-3, seed=RANDOM_STATE):
        self.epochs, self.batch_size, self.lr = epochs, batch_size, lr
        torch.manual_seed(seed)
        self.model = None
        self.x_mean = None
        self.x_std = None

    def _split_xy(self, X):
        X = np.asarray(X, dtype=np.float32)
        seq = X[:, :3][:, :, None]
        aux = X[:, 3:]
        return seq, aux

    def fit(self, X, y):
        X = np.asarray(X, dtype=np.float32)
        self.x_mean = X.mean(axis=0, keepdims=True)
        self.x_std = X.std(axis=0, keepdims=True) + 1e-8
        Xn = (X - self.x_mean) / self.x_std
        seq, aux = self._split_xy(Xn)
        y = np.asarray(y, dtype=np.float32)

        self.model = ReturnRNN(n_aux=aux.shape[1])
        opt = torch.optim.Adam(self.model.parameters(), lr=self.lr)
        loss_fn = nn.MSELoss()

        seq_t = torch.tensor(seq)
        aux_t = torch.tensor(aux)
        y_t = torch.tensor(y)
        n = len(y_t)

        self.model.train()
        for _epoch in range(self.epochs):
            perm = torch.randperm(n)
            for i in range(0, n, self.batch_size):
                idx = perm[i:i + self.batch_size]
                opt.zero_grad()
                pred = self.model(seq_t[idx], aux_t[idx])
                loss = loss_fn(pred, y_t[idx])
                loss.backward()
                opt.step()
        return self

    def predict(self, X):
        X = np.asarray(X, dtype=np.float32)
        Xn = (X - self.x_mean) / self.x_std
        seq, aux = self._split_xy(Xn)
        self.model.eval()
        with torch.no_grad():
            pred = self.model(torch.tensor(seq), torch.tensor(aux)).numpy()
        return pred

def make_rnn():
    return RNNRegressor()

MODEL_FEATURE_ORDER = SEQ_FEATURES + AUX_FEATURES
MODEL_FACTORY = {
    "RF": make_rf, "AdaBoost": make_adaboost, "XGBoost": make_xgboost,
    "SVR": make_svr, "KNN": make_knn, "RNN": make_rnn,
}


## 4. Prediction experiments

Reproduces **Table 2** (accuracy by train/test split), **Table 3**
(mean/std/variance at each model's empirically best split, from 5 repeated
random splits), and **Table 4** (top-10 predicted stocks per model, ranked
from each model's forward prediction on the most recent available month).

**Documented assumption:** "best split" is chosen empirically here (lowest
test RMSE on this feature set).

In [5]:

SPLITS = [0.1, 0.2, 0.3, 0.4]
N_REPEATS = 5

def metrics(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    return mae, mse, rmse

X_all = panel[MODEL_FEATURE_ORDER].values
y_all = panel["target_return"].values

rows = []
for model_name, factory in MODEL_FACTORY.items():
    for frac in SPLITS:
        Xtr, Xte, ytr, yte = train_test_split(X_all, y_all, test_size=frac, random_state=SEED)
        model = factory()
        model.fit(Xtr, ytr)
        pred = model.predict(Xte)
        mae, mse, rmse = metrics(yte, pred)
        rows.append({"Model": model_name, "Test set fraction": frac,
                     "MAE": mae, "MSE": mse, "RMSE": rmse})
        print(f"[split-table] {model_name:9s} frac={frac:.1f}  MAE={mae:.6f} MSE={mse:.6f} RMSE={rmse:.6f}")

table2 = pd.DataFrame(rows)
table2.to_csv(f"{OUT}/table2_prediction_by_split.csv", index=False)
display(table2)

[split-table] RF        frac=0.1  MAE=0.055734 MSE=0.006112 RMSE=0.078182

[split-table] RF        frac=0.2  MAE=0.054816 MSE=0.005944 RMSE=0.077096

[split-table] RF        frac=0.3  MAE=0.054382 MSE=0.005746 RMSE=0.075800

[split-table] RF        frac=0.4  MAE=0.054416 MSE=0.005717 RMSE=0.075613

[split-table] AdaBoost  frac=0.1  MAE=0.062049 MSE=0.007375 RMSE=0.085880

[split-table] AdaBoost  frac=0.2  MAE=0.060591 MSE=0.007144 RMSE=0.084522

[split-table] AdaBoost  frac=0.3  MAE=0.065904 MSE=0.007784 RMSE=0.088228

[split-table] AdaBoost  frac=0.4  MAE=0.061843 MSE=0.006929 RMSE=0.083239
[split-table] XGBoost   frac=0.1  MAE=0.060272 MSE=0.007325 RMSE=0.085584

[split-table] XGBoost   frac=0.2  MAE=0.059383 MSE=0.007045 RMSE=0.083937
[split-table] XGBoost   frac=0.3  MAE=0.059054 MSE=0.006915 RMSE=0.083154
[split-table] XGBoost   frac=0.4  MAE=0.059234 MSE=0.006891 RMSE=0.083011

[split-table] SVR       frac=0.1  MAE=0.057889 MSE=0.006600 RMSE=0.081240

[split-table] SVR       frac=0.2  MAE=0.056891 MSE=0.006371 RMSE=0.079821

[split-table] SVR       frac=0.3  MAE=0.056484 MSE=0.006177 RMSE=0.078597

[split-table] SVR       frac=0.4  MAE=0.056527 MSE=0.006123 RMSE=0.078250
[split-table] KNN       frac=0.1  MAE=0.064356 MSE=0.007711 RMSE=0.087812
[split-table] KNN       frac=0.2  MAE=0.064718 MSE=0.008102 RMSE=0.090011

[split-table] KNN       frac=0.3  MAE=0.064888 MSE=0.008054 RMSE=0.089743
[split-table] KNN       frac=0.4  MAE=0.064935 MSE=0.007976 RMSE=0.089310

[split-table] RNN       frac=0.1  MAE=0.057584 MSE=0.006505 RMSE=0.080655

[split-table] RNN       frac=0.2  MAE=0.057392 MSE=0.006442 RMSE=0.080260

[split-table] RNN       frac=0.3  MAE=0.057042 MSE=0.006382 RMSE=0.079886

[split-table] RNN       frac=0.4  MAE=0.057567 MSE=0.006272 RMSE=0.079193

       Model  Test set fraction       MAE       MSE      RMSE
0         RF                0.1  0.055734  0.006112  0.078182
1         RF                0.2  0.054816  0.005944  0.077096
2         RF                0.3  0.054382  0.005746  0.075800
3         RF                0.4  0.054416  0.005717  0.075613
4   AdaBoost                0.1  0.062049  0.007375  0.085880
5   AdaBoost                0.2  0.060591  0.007144  0.084522
6   AdaBoost                0.3  0.065904  0.007784  0.088228
7   AdaBoost                0.4  0.061843  0.006929  0.083239
8    XGBoost                0.1  0.060272  0.007325  0.085584
9    XGBoost                0.2  0.059383  0.007045  0.083937
10   XGBoost                0.3  0.059054  0.006915  0.083154
11   XGBoost                0.4  0.059234  0.006891  0.083011
12       SVR                0.1  0.057889  0.006600  0.081240
13       SVR                0.2  0.056891  0.006371  0.079821
14       SVR                0.3  0.056484  0.006177  0.078597
15       SVR                0.4  0.056527  0.006123  0.078250
16       KNN                0.1  0.064356  0.007711  0.087812
17       KNN                0.2  0.064718  0.008102  0.090011
18       KNN                0.3  0.064888  0.008054  0.089743
19       KNN                0.4  0.064935  0.007976  0.089310
20       RNN                0.1  0.057584  0.006505  0.080655
21       RNN                0.2  0.057392  0.006442  0.080260
22       RNN                0.3  0.057042  0.006382  0.079886
23       RNN                0.4  0.057567  0.006272  0.079193

In [6]:

idx = table2.groupby("Model")["RMSE"].idxmin()
best = table2.loc[idx, ["Model", "Test set fraction"]].reset_index(drop=True)
best_split = dict(zip(best["Model"], best["Test set fraction"]))
print("Best split per model (empirical, lowest test RMSE):", best_split)
with open(f"{OUT}/best_split_per_model.json", "w") as f:
    json.dump(best_split, f, indent=2)

Best split per model (empirical, lowest test RMSE): {'AdaBoost': 0.4, 'KNN': 0.1, 'RF': 0.4, 'RNN': 0.4, 'SVR': 0.4, 'XGBoost': 0.4}

In [7]:

rows = []
for model_name, factory in MODEL_FACTORY.items():
    frac = best_split[model_name]
    maes, mses, rmses = [], [], []
    for rep in range(N_REPEATS):
        Xtr, Xte, ytr, yte = train_test_split(X_all, y_all, test_size=frac, random_state=SEED + rep)
        model = factory()
        model.fit(Xtr, ytr)
        pred = model.predict(Xte)
        mae, mse, rmse = metrics(yte, pred)
        maes.append(mae); mses.append(mse); rmses.append(rmse)
    for stat_name, arr in [("mean", np.mean), ("sigma", np.std), ("sigma2", np.var)]:
        rows.append({
            "Model": model_name, "best_split_test_fraction": frac, "stat": stat_name,
            "MAE": arr(maes), "MSE": arr(mses), "RMSE": arr(rmses),
        })
    print(f"[summary] {model_name:9s} best_split={frac:.1f}  mean RMSE={np.mean(rmses):.6f}  sigma RMSE={np.std(rmses):.6f}")

table3 = pd.DataFrame(rows)
table3.to_csv(f"{OUT}/table3_prediction_summary.csv", index=False)
display(table3)

[summary] RF        best_split=0.4  mean RMSE=0.075582  sigma RMSE=0.000387

[summary] AdaBoost  best_split=0.4  mean RMSE=0.090049  sigma RMSE=0.005512

[summary] XGBoost   best_split=0.4  mean RMSE=0.083254  sigma RMSE=0.000857

[summary] SVR       best_split=0.4  mean RMSE=0.078112  sigma RMSE=0.000932

[summary] KNN       best_split=0.1  mean RMSE=0.087356  sigma RMSE=0.003503

[summary] RNN       best_split=0.4  mean RMSE=0.128358  sigma RMSE=0.086852

,Model,best_split_test_fraction,stat,MAE,MSE,RMSE
0,RF,0.4,mean,5.398028e-02,5.712823e-03,7.558223e-02
1,RF,0.4,sigma,2.645931e-04,5.863338e-05,3.873279e-04
2,RF,0.4,sigma2,7.000948e-08,3.437873e-09,1.500229e-07
3,AdaBoost,0.4,mean,6.656506e-02,8.139112e-03,9.004851e-02
4,AdaBoost,0.4,sigma,3.785237e-03,9.883654e-04,5.511504e-03
5,AdaBoost,0.4,sigma2,1.432802e-05,9.768662e-07,3.037668e-05
6,XGBoost,0.4,mean,5.882674e-02,6.931886e-03,8.325354e-02
7,XGBoost,0.4,sigma,3.970880e-04,1.425362e-04,8.567224e-04
8,XGBoost,0.4,sigma2,1.576789e-07,2.031656e-08,7.339732e-07
9,SVR,0.4,mean,5.611854e-02,6.102357e-03,7.811202e-02
10,SVR,0.4,sigma,3.577379e-04,1.461203e-04,9.322711e-04
11,SVR,0.4,sigma2,1.279764e-07,2.135115e-08,8.691293e-07
12,KNN,0.1,mean,6.318464e-02,7.643422e-03,8.735646e-02
13,KNN,0.1,sigma,9.026731e-04,6.233345e-04,3.503114e-03
14,KNN,0.1,sigma2,8.148188e-07,3.885459e-07,1.227181e-05
15,RNN,0.4,mean,5.799349e-02,2.401910e-02,1.283584e-01
16,RNN,0.4,sigma,1.942972e-03,3.339034e-02,8.685167e-02
17,RNN,0.4,sigma2,3.775140e-06,1.114915e-03,7.543212e-03

In [8]:

top_n = 10
latest = latest_feature_snapshot(panel)
X_latest = latest[MODEL_FEATURE_ORDER].values

all_preds = {"Company": latest["Company"].values}
top_tables = {}
for model_name, factory in MODEL_FACTORY.items():
    frac = best_split[model_name]
    Xtr, _, ytr, _ = train_test_split(X_all, y_all, test_size=frac, random_state=SEED)
    model = factory()
    model.fit(Xtr, ytr)
    preds = model.predict(X_latest)
    all_preds[model_name] = preds

    ranked = latest.assign(pred_return=preds).sort_values("pred_return", ascending=False)
    top_tables[model_name] = ranked[["Company", "pred_return"]].head(top_n).reset_index(drop=True)
    print(f"[top10] {model_name}: {list(top_tables[model_name]['Company'])}")

preds_df = pd.DataFrame(all_preds)
preds_df.to_csv(f"{OUT}/predictions_latest.csv", index=False)

table4 = pd.DataFrame({name: tbl["Company"].tolist() for name, tbl in top_tables.items()})
table4.to_csv(f"{OUT}/table4_top10_stocks.csv", index=False)
for name, tbl in top_tables.items():
    tbl.to_csv(f"{OUT}/top10_detail_{name}.csv", index=False)

display(table4)

[top10] RF: ['MLM', 'FLT', 'ZTS', 'LYV', 'XYL', 'CHRW', 'PCAR', 'TSLA', 'ROP', 'HPQ']

[top10] AdaBoost: ['DISH', 'ALB', 'URI', 'ABBV', 'TT', 'SYK', 'BKNG', 'STLD', 'TDG', 'TSLA']
[top10] XGBoost: ['ZTS', 'A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABT', 'ACGL', 'ACN']

[top10] SVR: ['DISH', 'FSLR', 'MKTX', 'ENPH', 'MTCH', 'VLO', 'CTLT', 'ILMN', 'INTC', 'TSLA']
[top10] KNN: ['ON', 'MPWR', 'ETSY', 'MLM', 'NVDA', 'VRSK', 'ZTS', 'MCHP', 'LYV', 'GNRC']

[top10] RNN: ['CTLT', 'TSLA', 'FSLR', 'MKTX', 'ALB', 'CRL', 'NTAP', 'DISH', 'JBHT', 'ENPH']

     RF AdaBoost XGBoost   SVR   KNN   RNN
0   MLM     DISH     ZTS  DISH    ON  CTLT
1   FLT      ALB       A  FSLR  MPWR  TSLA
2   ZTS      URI     AAL  MKTX  ETSY  FSLR
3   LYV     ABBV     AAP  ENPH   MLM  MKTX
4   XYL       TT    AAPL  MTCH  NVDA   ALB
5  CHRW      SYK    ABBV   VLO  VRSK   CRL
6  PCAR     BKNG     ABC  CTLT   ZTS  NTAP
7  TSLA     STLD     ABT  ILMN  MCHP  DISH
8   ROP      TDG    ACGL  INTC   LYV  JBHT
9   HPQ     TSLA     ACN  TSLA  GNRC  ENPH

In [9]:

# Sanity check flagged in the manuscript: XGBoost's Table-1 hyperparameters
# (learning_rate=0.01, gamma=2) can make its forward predictions collapse to
# an almost-constant value on this feature set.
print(preds_df["XGBoost"].describe())
print("unique XGBoost predictions:", preds_df["XGBoost"].nunique())

count    491.000000
mean      -0.005788
std        0.000144
min       -0.008979
25%       -0.005781
50%       -0.005781
75%       -0.005781
max       -0.005781
Name: XGBoost, dtype: float64
unique XGBoost predictions: 2


## 5. Figure 3 -- candidate-pool monthly returns

One panel per model (small multiples), each showing only its own top-10
candidate pool (<=10 lines). Distinguishing 45+ overlapping lines by colour
alone on a single axes is not achievable at any palette size, so each panel
is restricted to a traceable number of series and a shared y-axis keeps the
panels visually comparable.

In [10]:

wide, date_map = wide_returns()

MODELS = ["RF", "AdaBoost", "XGBoost", "SVR", "KNN", "RNN"]
per_model = {}
union = set()
for m in MODELS:
    df = pd.read_csv(f"{OUT}/top10_detail_{m}.csv")
    companies = df["Company"].tolist()
    per_model[m] = companies
    union.update(companies)
union = sorted(union)
print(f"Union of top-10 stocks across all 6 models: {len(union)} unique companies")

dates = date_map.loc[wide.index]
labels = [f"{int(y)}-{int(mo):02d}" for y, mo in zip(dates["Year"], dates["Month"])]
tick_idx = np.linspace(0, len(wide.index) - 1, 8, dtype=int)

all_vals = wide[union].values
ymin, ymax = np.nanmin(all_vals), np.nanmax(all_vals)
pad = 0.05 * (ymax - ymin)
ylim = (ymin - pad, ymax + pad)

tab10 = plt.get_cmap("tab10").colors
markers = ["o", "s", "^", "D", "v", "P", "X", "*", "<", ">"]

fig, axes = plt.subplots(2, 3, figsize=(16, 9), sharex=True, sharey=True)
for ax, model_name in zip(axes.flat, MODELS):
    companies = per_model[model_name]
    for i, c in enumerate(companies):
        ax.plot(
            wide.index, wide[c].values,
            color=tab10[i % 10], marker=markers[i % 10], markersize=3,
            markevery=6, linewidth=1.4, alpha=0.9, label=c,
        )
    ax.axhline(0, color="black", linewidth=0.6, alpha=0.5, zorder=0)
    ax.set_title(f"{model_name} top-10 pool", fontsize=11, fontweight="bold")
    ax.set_ylim(*ylim)
    ax.set_xticks(wide.index[tick_idx])
    ax.set_xticklabels([labels[i] for i in tick_idx], rotation=45, ha="right", fontsize=8)
    ax.legend(fontsize=7, ncol=2, loc="upper left", framealpha=0.85)
    ax.grid(alpha=0.25, linewidth=0.5)

for ax in axes[:, 0]:
    ax.set_ylabel("Monthly return", fontsize=9)
for ax in axes[-1, :]:
    ax.set_xlabel("Month", fontsize=9)

fig.suptitle(
    f"Monthly returns of each model's top-10 predicted-return candidate pool "
    f"(union across all six models: {len(union)} distinct companies)",
    fontsize=13,
)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig(f"{OUT}/fig3_monthly_returns.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"saved {OUT}/fig3_monthly_returns.png")

Union of top-10 stocks across all 6 models: 45 unique companies

saved outputs/fig3_monthly_returns.png


## 6. Elastic-net regularised mean-variance portfolio (EN-MVP) + simulated annealing

Implements Eq. (11) of the manuscript and the joint `(x, r)` simulated-
annealing solver of Algorithm 1:

$$
\min_{x,r}\ \lambda (x^\top \Sigma x) - (1-\lambda)(\mu^\top x)
+ \alpha\Big(r \sum_i |x_i| + \tfrac{1-r}{2}\sum_i x_i^2\Big)
\quad\text{s.t.}\quad \sum_i x_i = 1,\ 0\le x_i\le 1,\ 0\le r\le 1
$$

In [11]:

def objective(x, r, mu, sigma, lam, alpha):
    var_term = x @ sigma @ x
    ret_term = mu @ x
    l1 = np.sum(np.abs(x))
    l2 = np.sum(x ** 2)
    penalty = alpha * (r * l1 + (1 - r) / 2 * l2)
    return lam * var_term - (1 - lam) * ret_term + penalty

def _project_simplex(v):
    n = len(v)
    u = np.sort(v)[::-1]
    css = np.cumsum(u) - 1
    idx = np.arange(1, n + 1)
    cond = u - css / idx > 0
    rho = idx[cond][-1]
    theta = css[cond][-1] / rho
    w = np.maximum(v - theta, 0)
    return w

def simulated_annealing(mu, sigma, lam, alpha, n_assets=None, seed=0,
                         T0=1000.0, Tf=0.01, beta=0.99, inner_iter=100,
                         step_x=0.05, step_r=0.05):
    rng = np.random.default_rng(seed)
    n = len(mu) if n_assets is None else n_assets

    x = _project_simplex(rng.random(n))
    r = rng.uniform(0, 1)
    f = objective(x, r, mu, sigma, lam, alpha)
    x_best, r_best, f_best = x.copy(), r, f

    T = T0
    while T > Tf:
        for _ in range(inner_iter):
            x_new = _project_simplex(x + rng.normal(0, step_x, size=n))
            r_new = np.clip(r + rng.normal(0, step_r), 0, 1)
            f_new = objective(x_new, r_new, mu, sigma, lam, alpha)
            df = f_new - f
            if df <= 0 or rng.random() < np.exp(-df / T):
                x, r, f = x_new, r_new, f_new
                if f < f_best:
                    x_best, r_best, f_best = x.copy(), r, f
        T *= beta

    # Apply the same 0.01 convergence threshold used in the manuscript to
    # report "zero" weights (the L1 term is non-smooth, so SA does not
    # converge individual weights to exactly zero in finite iterations).
    x_report = x_best.copy()
    x_report[x_report < 0.01] = 0.0
    if x_report.sum() > 0:
        x_report = x_report / x_report.sum()

    return x_report, r_best, f_best

def sharpe_ratio(mean_return, std_return, rf=0.0):
    if std_return == 0:
        return np.nan
    return (mean_return - rf) / std_return

def equal_weight(n):
    return np.ones(n) / n

def run_sa_multi(mu, sigma, lam, alpha, n_runs=10, seed0=0, **kwargs):
    xs, rs, fs = [], [], []
    for k in range(n_runs):
        x, r, f = simulated_annealing(mu, sigma, lam, alpha, seed=seed0 + k, **kwargs)
        xs.append(x); rs.append(r); fs.append(f)
    x_mean = np.mean(xs, axis=0)
    if x_mean.sum() > 0:
        x_mean = x_mean / x_mean.sum()
    return x_mean, float(np.mean(rs)), float(np.mean(fs)), np.array(xs), np.array(rs), np.array(fs)

In [12]:

# Quick sanity check on synthetic data before trusting the solver on real portfolios.
rng = np.random.default_rng(0)
n = 10
mu_syn = rng.uniform(-0.02, 0.05, n)
A = rng.normal(0, 0.05, (n, 20))
sigma_syn = A @ A.T / 20 + np.eye(n) * 1e-4

x, r, f = simulated_annealing(mu_syn, sigma_syn, lam=0.99, alpha=0.001, seed=1)
print("SA weights:", np.round(x, 4), "sum:", x.sum())
print("SA r*:", r, " SA objective:", f)
print("Equal-weight objective (for comparison):",
      objective(equal_weight(n), 0.5, mu_syn, sigma_syn, 0.99, 0.001))

SA weights: [0.1453 0.0245 0.     0.     0.0944 0.2019 0.     0.0737 0.2822 0.1781] sum: 1.0
SA r*: 0.000554030041643519  SA objective: -3.4517534372510415e-05
Equal-weight objective (for comparison): 0.0005047370191621583


## 7. Calibrating the regularisation strength alpha

`alpha=0.06`, carried over from Yen & Yen (2014)'s reported optimum for a
*different* dataset, dominates the risk-return trade-off terms of Eq. (11)
so completely at this sample's return/covariance scale that the SA-optimised
mixing parameter `r*` collapses to ~0 for every predictor/regime combination
-- no weight is ever driven below the sparsity threshold, and the elastic-net
penalty degenerates to pure ridge.

This section resolves that with the small validation grid search the
manuscript's methodology calls for: the 65-month sample is split
chronologically into a 48-month **train window** (Jan 2018-Dec 2021, used
only to estimate the covariance matrix) and a 17-month **validation window**
(Jan 2022-May 2023, used only to score candidate alpha values), so the
selected alpha is chosen by realised out-of-window performance rather than
in-sample fit. `mu` (predicted expected return) is the same forward snapshot
used throughout (Section 4 above); it is not re-estimated per window,
consistent with the rest of the pipeline (see Limitations).

For each candidate alpha, weights are solved by the same joint `(x, r)`
simulated annealing (Algorithm 1) using `Sigma_train` and each model's `mu`,
for all 6 predictors x 2 risk regimes, and scored on the validation window's
realised Sharpe ratio and cumulative return against the equal-weight (1/N)
benchmark on the same candidate pool.

**Documented compute deviation:** this search uses reduced SA settings
(`n_runs=3`, `inner_iter=50` instead of the manuscript's 10 runs / 100 inner
iterations) purely for tractability in a 2-core environment -- exactly like
the RF `max_features` / RNN epoch deviations in Table 1. Section 8 below,
which produces the manuscript's actually-reported tables/figures, uses the
full SA settings at the selected alpha.

In [13]:

ALPHA_GRID = [0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03, 0.06]
SEARCH_LAMBDAS = [0.01, 0.99]
N_SEARCH_RUNS = 3
SEARCH_KWARGS = dict(inner_iter=50)
TRAIN_END = 48   # months 0..47 -> covariance estimation window; 48..64 -> validation

n_months = wide.shape[0]
print(f"train window: months 0-{TRAIN_END - 1} ({TRAIN_END} months); "
      f"validation window: months {TRAIN_END}-{n_months - 1} ({n_months - TRAIN_END} months)")

def portfolio_series(weights, returns_df):
    R = returns_df.fillna(0.0).values
    return R @ weights

def cumulative_return(monthly_returns):
    return np.cumprod(1 + monthly_returns) - 1

alpha_records = []
t_start = time.time()
for alpha in ALPHA_GRID:
    for model_name in MODELS:
        pool = pd.read_csv(f"{OUT}/top10_detail_{model_name}.csv").head(10)
        companies = pool["Company"].tolist()
        mu = pool["pred_return"].values
        sub_train = wide[companies].iloc[:TRAIN_END]
        sub_val = wide[companies].iloc[TRAIN_END:]
        sigma_train = sub_train.cov().values

        for lam in SEARCH_LAMBDAS:
            xs, rs = [], []
            for k in range(N_SEARCH_RUNS):
                x, r, f = simulated_annealing(
                    mu, sigma_train, lam=lam, alpha=alpha,
                    seed=2000 + k, **SEARCH_KWARGS)
                xs.append(x); rs.append(r)
            x_mean = np.mean(xs, axis=0)
            if x_mean.sum() > 0:
                x_mean = x_mean / x_mean.sum()
            r_mean = float(np.mean(rs))
            n_zero = int(np.sum(x_mean < 0.01))

            en_val = portfolio_series(x_mean, sub_val)
            ew_val = portfolio_series(equal_weight(len(companies)), sub_val)
            en_mean, en_std = np.nanmean(en_val), np.nanstd(en_val)
            ew_mean, ew_std = np.nanmean(ew_val), np.nanstd(ew_val)
            en_sharpe = sharpe_ratio(en_mean, en_std)
            ew_sharpe = sharpe_ratio(ew_mean, ew_std)
            en_cum = cumulative_return(en_val)[-1]
            ew_cum = cumulative_return(ew_val)[-1]

            rec = dict(alpha=alpha, model=model_name, lam=lam,
                       r_star=r_mean, n_zero_weights=n_zero,
                       val_sharpe_en=en_sharpe, val_sharpe_ew=ew_sharpe,
                       val_cumret_en=en_cum, val_cumret_ew=ew_cum,
                       beats_1N_sharpe=int(en_sharpe > ew_sharpe),
                       beats_1N_cumret=int(en_cum > ew_cum))
            alpha_records.append(rec)
            elapsed = time.time() - t_start
            print(f"[{elapsed:6.0f}s] alpha={alpha:<8} {model_name:9s} lam={lam:<5} "
                  f"r*={r_mean:.4f} zero_w={n_zero} "
                  f"val_Sharpe(EN)={en_sharpe:+.3f} val_Sharpe(1/N)={ew_sharpe:+.3f} "
                  f"beats1N={rec['beats_1N_sharpe']}")

            pd.DataFrame(alpha_records).to_csv(f"{OUT}/alpha_search_log.csv", index=False)

alpha_df = pd.DataFrame(alpha_records)
alpha_summary = alpha_df.groupby("alpha").agg(
    mean_val_sharpe_en=("val_sharpe_en", "mean"),
    mean_val_sharpe_ew=("val_sharpe_ew", "mean"),
    mean_r_star=("r_star", "mean"),
    mean_zero_weights=("n_zero_weights", "mean"),
    win_rate_sharpe=("beats_1N_sharpe", "mean"),
    win_rate_cumret=("beats_1N_cumret", "mean"),
).reset_index()
alpha_summary.to_csv(f"{OUT}/alpha_search_summary.csv", index=False)

print("\n=== Summary by alpha (validation window, months 48-64) ===")
display(alpha_summary)

# Selection criterion: win rate against 1/N on validation Sharpe ratio, NOT
# raw mean validation Sharpe. The two disagree here: mean Sharpe is actually
# maximised at alpha=0.06 (the original, uncalibrated value), but that alpha
# also drives r* back to its degenerate near-zero value and produces almost
# no sparsity -- exactly the failure mode this search exists to correct.
# Win rate is the criterion reported and used throughout the manuscript.
BEST_ALPHA = alpha_summary.loc[alpha_summary["win_rate_sharpe"].idxmax(), "alpha"]
best_row = alpha_summary.loc[alpha_summary["alpha"] == BEST_ALPHA].iloc[0]
degenerate_row = alpha_summary.loc[alpha_summary["alpha"] == alpha_summary["alpha"].max()].iloc[0]
print(f"\nRecommended alpha (highest win rate against 1/N on validation "
      f"Sharpe ratio, {int(round(best_row['win_rate_sharpe'] * 12))} of 12 "
      f"model/regime combinations, mean r*={best_row['mean_r_star']:.4f}): {BEST_ALPHA}")
print(f"(Mean validation Sharpe alone is maximised at alpha="
      f"{degenerate_row['alpha']}, but that alpha leaves r* at its "
      f"degenerate value -- mean r*={degenerate_row['mean_r_star']:.4f} -- "
      f"and yields almost no sparsity -- mean near-zero weights="
      f"{degenerate_row['mean_zero_weights']:.2f} of 10 -- so it is not "
      f"selected; see the manuscript's Section 6.2 for the full rationale.)")

train window: months 0-47 (48 months); validation window: months 48-63 (16 months)

[     7s] alpha=0.0001   RF        lam=0.01  r*=0.5841 zero_w=2 val_Sharpe(EN)=+0.051 val_Sharpe(1/N)=-0.006 beats1N=1

[    14s] alpha=0.0001   RF        lam=0.99  r*=0.1599 zero_w=3 val_Sharpe(EN)=+0.044 val_Sharpe(1/N)=-0.006 beats1N=1

[    22s] alpha=0.0001   AdaBoost  lam=0.01  r*=0.6580 zero_w=4 val_Sharpe(EN)=-0.372 val_Sharpe(1/N)=+0.022 beats1N=0

[    29s] alpha=0.0001   AdaBoost  lam=0.99  r*=0.3307 zero_w=4 val_Sharpe(EN)=+0.150 val_Sharpe(1/N)=+0.022 beats1N=1

[    36s] alpha=0.0001   XGBoost   lam=0.01  r*=0.0000 zero_w=3 val_Sharpe(EN)=+0.194 val_Sharpe(1/N)=+0.019 beats1N=1

[    43s] alpha=0.0001   XGBoost   lam=0.99  r*=0.1064 zero_w=4 val_Sharpe(EN)=+0.162 val_Sharpe(1/N)=+0.019 beats1N=1

[    51s] alpha=0.0001   SVR       lam=0.01  r*=0.7651 zero_w=5 val_Sharpe(EN)=-0.594 val_Sharpe(1/N)=-0.134 beats1N=0

[    59s] alpha=0.0001   SVR       lam=0.99  r*=0.5934 zero_w=4 val_Sharpe(EN)=-0.150 val_Sharpe(1/N)=-0.134 beats1N=0

[    66s] alpha=0.0001   KNN       lam=0.01  r*=0.4335 zero_w=4 val_Sharpe(EN)=+0.180 val_Sharpe(1/N)=+0.011 beats1N=1

[    73s] alpha=0.0001   KNN       lam=0.99  r*=0.3680 zero_w=3 val_Sharpe(EN)=+0.047 val_Sharpe(1/N)=+0.011 beats1N=1

[    81s] alpha=0.0001   RNN       lam=0.01  r*=0.2240 zero_w=4 val_Sharpe(EN)=-0.179 val_Sharpe(1/N)=-0.094 beats1N=0

[    88s] alpha=0.0001   RNN       lam=0.99  r*=0.5649 zero_w=4 val_Sharpe(EN)=-0.059 val_Sharpe(1/N)=-0.094 beats1N=1

[    96s] alpha=0.0003   RF        lam=0.01  r*=0.5093 zero_w=4 val_Sharpe(EN)=+0.047 val_Sharpe(1/N)=-0.006 beats1N=1

[   103s] alpha=0.0003   RF        lam=0.99  r*=0.0292 zero_w=3 val_Sharpe(EN)=+0.070 val_Sharpe(1/N)=-0.006 beats1N=1

[   110s] alpha=0.0003   AdaBoost  lam=0.01  r*=0.6909 zero_w=5 val_Sharpe(EN)=-0.074 val_Sharpe(1/N)=+0.022 beats1N=0

[   118s] alpha=0.0003   AdaBoost  lam=0.99  r*=0.1747 zero_w=4 val_Sharpe(EN)=+0.165 val_Sharpe(1/N)=+0.022 beats1N=1

[   125s] alpha=0.0003   XGBoost   lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.096 val_Sharpe(1/N)=+0.019 beats1N=1

[   132s] alpha=0.0003   XGBoost   lam=0.99  r*=0.0481 zero_w=4 val_Sharpe(EN)=+0.156 val_Sharpe(1/N)=+0.019 beats1N=1

[   139s] alpha=0.0003   SVR       lam=0.01  r*=0.4247 zero_w=3 val_Sharpe(EN)=-0.672 val_Sharpe(1/N)=-0.134 beats1N=0

[   147s] alpha=0.0003   SVR       lam=0.99  r*=0.1096 zero_w=3 val_Sharpe(EN)=-0.155 val_Sharpe(1/N)=-0.134 beats1N=0

[   154s] alpha=0.0003   KNN       lam=0.01  r*=0.7145 zero_w=5 val_Sharpe(EN)=+0.178 val_Sharpe(1/N)=+0.011 beats1N=1

[   161s] alpha=0.0003   KNN       lam=0.99  r*=0.0416 zero_w=2 val_Sharpe(EN)=+0.048 val_Sharpe(1/N)=+0.011 beats1N=1

[   169s] alpha=0.0003   RNN       lam=0.01  r*=0.5363 zero_w=4 val_Sharpe(EN)=-0.203 val_Sharpe(1/N)=-0.094 beats1N=0

[   176s] alpha=0.0003   RNN       lam=0.99  r*=0.1512 zero_w=5 val_Sharpe(EN)=-0.081 val_Sharpe(1/N)=-0.094 beats1N=1

[   183s] alpha=0.001    RF        lam=0.01  r*=0.5335 zero_w=2 val_Sharpe(EN)=+0.058 val_Sharpe(1/N)=-0.006 beats1N=1

[   190s] alpha=0.001    RF        lam=0.99  r*=0.0000 zero_w=2 val_Sharpe(EN)=+0.059 val_Sharpe(1/N)=-0.006 beats1N=1

[   197s] alpha=0.001    AdaBoost  lam=0.01  r*=0.6810 zero_w=5 val_Sharpe(EN)=-0.368 val_Sharpe(1/N)=+0.022 beats1N=0

[   205s] alpha=0.001    AdaBoost  lam=0.99  r*=0.1166 zero_w=1 val_Sharpe(EN)=+0.185 val_Sharpe(1/N)=+0.022 beats1N=1

[   212s] alpha=0.001    XGBoost   lam=0.01  r*=0.0009 zero_w=0 val_Sharpe(EN)=+0.037 val_Sharpe(1/N)=+0.019 beats1N=1

[   219s] alpha=0.001    XGBoost   lam=0.99  r*=0.0149 zero_w=1 val_Sharpe(EN)=+0.177 val_Sharpe(1/N)=+0.019 beats1N=1

[   227s] alpha=0.001    SVR       lam=0.01  r*=0.4453 zero_w=4 val_Sharpe(EN)=-0.703 val_Sharpe(1/N)=-0.134 beats1N=0

[   234s] alpha=0.001    SVR       lam=0.99  r*=0.2395 zero_w=3 val_Sharpe(EN)=-0.128 val_Sharpe(1/N)=-0.134 beats1N=1

[   241s] alpha=0.001    KNN       lam=0.01  r*=0.3051 zero_w=5 val_Sharpe(EN)=+0.185 val_Sharpe(1/N)=+0.011 beats1N=1

[   249s] alpha=0.001    KNN       lam=0.99  r*=0.0194 zero_w=2 val_Sharpe(EN)=+0.044 val_Sharpe(1/N)=+0.011 beats1N=1

[   256s] alpha=0.001    RNN       lam=0.01  r*=0.7358 zero_w=5 val_Sharpe(EN)=-0.200 val_Sharpe(1/N)=-0.094 beats1N=0

[   263s] alpha=0.001    RNN       lam=0.99  r*=0.0539 zero_w=3 val_Sharpe(EN)=-0.061 val_Sharpe(1/N)=-0.094 beats1N=1

[   270s] alpha=0.003    RF        lam=0.01  r*=0.0231 zero_w=3 val_Sharpe(EN)=+0.045 val_Sharpe(1/N)=-0.006 beats1N=1

[   278s] alpha=0.003    RF        lam=0.99  r*=0.0083 zero_w=2 val_Sharpe(EN)=+0.047 val_Sharpe(1/N)=-0.006 beats1N=1

[   285s] alpha=0.003    AdaBoost  lam=0.01  r*=0.4853 zero_w=5 val_Sharpe(EN)=-0.158 val_Sharpe(1/N)=+0.022 beats1N=0

[   293s] alpha=0.003    AdaBoost  lam=0.99  r*=0.0165 zero_w=3 val_Sharpe(EN)=+0.153 val_Sharpe(1/N)=+0.022 beats1N=1

[   300s] alpha=0.003    XGBoost   lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.029 val_Sharpe(1/N)=+0.019 beats1N=1

[   308s] alpha=0.003    XGBoost   lam=0.99  r*=0.0017 zero_w=1 val_Sharpe(EN)=+0.172 val_Sharpe(1/N)=+0.019 beats1N=1

[   315s] alpha=0.003    SVR       lam=0.01  r*=0.3656 zero_w=3 val_Sharpe(EN)=-0.686 val_Sharpe(1/N)=-0.134 beats1N=0

[   322s] alpha=0.003    SVR       lam=0.99  r*=0.0148 zero_w=2 val_Sharpe(EN)=-0.174 val_Sharpe(1/N)=-0.134 beats1N=0

[   330s] alpha=0.003    KNN       lam=0.01  r*=0.5624 zero_w=3 val_Sharpe(EN)=+0.182 val_Sharpe(1/N)=+0.011 beats1N=1

[   337s] alpha=0.003    KNN       lam=0.99  r*=0.0090 zero_w=3 val_Sharpe(EN)=+0.035 val_Sharpe(1/N)=+0.011 beats1N=1

[   344s] alpha=0.003    RNN       lam=0.01  r*=0.2087 zero_w=4 val_Sharpe(EN)=-0.191 val_Sharpe(1/N)=-0.094 beats1N=0

[   351s] alpha=0.003    RNN       lam=0.99  r*=0.0261 zero_w=3 val_Sharpe(EN)=-0.068 val_Sharpe(1/N)=-0.094 beats1N=1

[   358s] alpha=0.01     RF        lam=0.01  r*=0.0132 zero_w=3 val_Sharpe(EN)=+0.022 val_Sharpe(1/N)=-0.006 beats1N=1

[   365s] alpha=0.01     RF        lam=0.99  r*=0.0000 zero_w=2 val_Sharpe(EN)=+0.050 val_Sharpe(1/N)=-0.006 beats1N=1

[   373s] alpha=0.01     AdaBoost  lam=0.01  r*=0.0291 zero_w=4 val_Sharpe(EN)=-0.094 val_Sharpe(1/N)=+0.022 beats1N=0

[   380s] alpha=0.01     AdaBoost  lam=0.99  r*=0.0000 zero_w=3 val_Sharpe(EN)=+0.173 val_Sharpe(1/N)=+0.022 beats1N=1

[   387s] alpha=0.01     XGBoost   lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.055 val_Sharpe(1/N)=+0.019 beats1N=1

[   394s] alpha=0.01     XGBoost   lam=0.99  r*=0.0000 zero_w=1 val_Sharpe(EN)=+0.149 val_Sharpe(1/N)=+0.019 beats1N=1

[   401s] alpha=0.01     SVR       lam=0.01  r*=0.0189 zero_w=3 val_Sharpe(EN)=-0.486 val_Sharpe(1/N)=-0.134 beats1N=0

[   408s] alpha=0.01     SVR       lam=0.99  r*=0.0000 zero_w=1 val_Sharpe(EN)=-0.171 val_Sharpe(1/N)=-0.134 beats1N=0

[   416s] alpha=0.01     KNN       lam=0.01  r*=0.1349 zero_w=3 val_Sharpe(EN)=+0.176 val_Sharpe(1/N)=+0.011 beats1N=1

[   424s] alpha=0.01     KNN       lam=0.99  r*=0.0000 zero_w=1 val_Sharpe(EN)=+0.025 val_Sharpe(1/N)=+0.011 beats1N=1

[   432s] alpha=0.01     RNN       lam=0.01  r*=0.0826 zero_w=3 val_Sharpe(EN)=-0.172 val_Sharpe(1/N)=-0.094 beats1N=0

[   439s] alpha=0.01     RNN       lam=0.99  r*=0.0000 zero_w=2 val_Sharpe(EN)=-0.109 val_Sharpe(1/N)=-0.094 beats1N=0

[   447s] alpha=0.03     RF        lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.003 val_Sharpe(1/N)=-0.006 beats1N=1

[   454s] alpha=0.03     RF        lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.062 val_Sharpe(1/N)=-0.006 beats1N=1

[   461s] alpha=0.03     AdaBoost  lam=0.01  r*=0.0101 zero_w=2 val_Sharpe(EN)=-0.251 val_Sharpe(1/N)=+0.022 beats1N=0

[   468s] alpha=0.03     AdaBoost  lam=0.99  r*=0.0002 zero_w=0 val_Sharpe(EN)=+0.175 val_Sharpe(1/N)=+0.022 beats1N=1

[   475s] alpha=0.03     XGBoost   lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.009 val_Sharpe(1/N)=+0.019 beats1N=0

[   482s] alpha=0.03     XGBoost   lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.115 val_Sharpe(1/N)=+0.019 beats1N=1

[   490s] alpha=0.03     SVR       lam=0.01  r*=0.0000 zero_w=3 val_Sharpe(EN)=-0.292 val_Sharpe(1/N)=-0.134 beats1N=0

[   497s] alpha=0.03     SVR       lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=-0.159 val_Sharpe(1/N)=-0.134 beats1N=0

[   504s] alpha=0.03     KNN       lam=0.01  r*=0.0313 zero_w=3 val_Sharpe(EN)=+0.172 val_Sharpe(1/N)=+0.011 beats1N=1

[   511s] alpha=0.03     KNN       lam=0.99  r*=0.0000 zero_w=1 val_Sharpe(EN)=+0.049 val_Sharpe(1/N)=+0.011 beats1N=1

[   518s] alpha=0.03     RNN       lam=0.01  r*=0.0024 zero_w=3 val_Sharpe(EN)=-0.122 val_Sharpe(1/N)=-0.094 beats1N=0

[   526s] alpha=0.03     RNN       lam=0.99  r*=0.0000 zero_w=2 val_Sharpe(EN)=-0.127 val_Sharpe(1/N)=-0.094 beats1N=0

[   534s] alpha=0.06     RF        lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=-0.020 val_Sharpe(1/N)=-0.006 beats1N=0

[   541s] alpha=0.06     RF        lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.023 val_Sharpe(1/N)=-0.006 beats1N=1

[   549s] alpha=0.06     AdaBoost  lam=0.01  r*=0.0000 zero_w=1 val_Sharpe(EN)=-0.238 val_Sharpe(1/N)=+0.022 beats1N=0

[   556s] alpha=0.06     AdaBoost  lam=0.99  r*=0.0002 zero_w=0 val_Sharpe(EN)=+0.132 val_Sharpe(1/N)=+0.022 beats1N=1

[   564s] alpha=0.06     XGBoost   lam=0.01  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.035 val_Sharpe(1/N)=+0.019 beats1N=1

[   571s] alpha=0.06     XGBoost   lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=+0.043 val_Sharpe(1/N)=+0.019 beats1N=1

[   578s] alpha=0.06     SVR       lam=0.01  r*=0.0000 zero_w=2 val_Sharpe(EN)=-0.157 val_Sharpe(1/N)=-0.134 beats1N=0

[   586s] alpha=0.06     SVR       lam=0.99  r*=0.0005 zero_w=0 val_Sharpe(EN)=-0.183 val_Sharpe(1/N)=-0.134 beats1N=0

[   593s] alpha=0.06     KNN       lam=0.01  r*=0.0260 zero_w=3 val_Sharpe(EN)=+0.169 val_Sharpe(1/N)=+0.011 beats1N=1

[   600s] alpha=0.06     KNN       lam=0.99  r*=0.0000 zero_w=0 val_Sharpe(EN)=-0.012 val_Sharpe(1/N)=+0.011 beats1N=0

[   608s] alpha=0.06     RNN       lam=0.01  r*=0.0000 zero_w=1 val_Sharpe(EN)=-0.040 val_Sharpe(1/N)=-0.094 beats1N=1

[   615s] alpha=0.06     RNN       lam=0.99  r*=0.0000 zero_w=1 val_Sharpe(EN)=-0.099 val_Sharpe(1/N)=-0.094 beats1N=0

=== Summary by alpha (validation window, months 48-64) ===

,alpha,mean_val_sharpe_en,mean_val_sharpe_ew,mean_r_star,mean_zero_weights,win_rate_sharpe,win_rate_cumret
0,0.0001,-0.043981,-0.030328,0.399001,3.666667,0.666667,0.666667
1,0.0003,-0.035367,-0.030328,0.285851,3.500000,0.666667,0.666667
2,0.0010,-0.059527,-0.030328,0.262154,2.750000,0.750000,0.666667
3,0.0030,-0.051150,-0.030328,0.143455,2.666667,0.666667,0.666667
4,0.0100,-0.031798,-0.030328,0.023218,2.166667,0.583333,0.666667
5,0.0300,-0.030576,-0.030328,0.003664,1.166667,0.500000,0.500000
6,0.0600,-0.028941,-0.030328,0.002234,0.666667,0.500000,0.583333

Recommended alpha (highest win rate against 1/N on validation Sharpe ratio, 9 of 12 model/regime combinations, mean r*=0.2622): 0.001
(Mean validation Sharpe alone is maximised at alpha=0.06, but that alpha leaves r* at its degenerate value -- mean r*=0.0022 -- and yields almost no sparsity -- mean near-zero weights=0.67 of 10 -- so it is not selected; see the manuscript's Section 6.2 for the full rationale.)


## 8. Portfolio experiments at the calibrated alpha

Builds the six EN-MVP hybrid portfolios (one per prediction model) from the
top-10 candidate pools above, using the calibrated `alpha=0.001` selected in
Section 7, at the manuscript's full SA settings (`T0=1000`, `Tf=0.01`,
`beta=0.99`, `inner_iter=100`; 10 randomised runs averaged for the
weight-allocation tables). Historical covariance and the realised-return
series used for the cumulative-return backtest are computed from the full
sample (Jan 2018-May 2023) -- an in-sample backtest, not an out-of-sample
rolling validation (see `README.md`, Limitations).

Reproduces:
- **Fig. 4**: mean return / std dev / Sharpe ratio vs. portfolio size
  *i* in {6,...,10}, at $\lambda=0.99$
- **Tables 5-6**: SA-optimised weight allocation, objective *F* and mixing
  parameter *r\**, at $\lambda=0.01$ and $\lambda=0.99$, *i*=10, averaged
  over 10 SA runs
- **Figs. 5-6**: cumulative return of each EN-MVP portfolio vs. its
  equal-weight (1/N) benchmark

In [14]:

ALPHA = 0.001  # calibrated in Section 7; see outputs/alpha_search_summary.csv
ASSET_COUNTS = [6, 7, 8, 9, 10]
LAMBDAS = [0.01, 0.99]
N_SA_RUNS = 10

def load_pool(model_name):
    return pd.read_csv(f"{OUT}/top10_detail_{model_name}.csv")

def sigma_for(companies, wide_df):
    sub = wide_df[companies]
    return sub.cov().values, sub

records = []
for model_name in MODELS:
    pool = load_pool(model_name)
    for i in ASSET_COUNTS:
        top_i = pool.head(i)
        companies = top_i["Company"].tolist()
        mu = top_i["pred_return"].values
        sigma, sub = sigma_for(companies, wide)

        x, r, f = simulated_annealing(mu, sigma, lam=0.99, alpha=ALPHA, seed=123)
        port_ret = portfolio_series(x, sub)
        mean_r, std_r = np.nanmean(port_ret), np.nanstd(port_ret)
        sr = sharpe_ratio(mean_r, std_r)

        records.append({"Model": model_name, "i": i, "mean_return": mean_r,
                         "std_return": std_r, "sharpe": sr, "r_star": r})
        print(f"[asset-count] {model_name:9s} i={i:2d}  mean={mean_r:+.5f} "
              f"std={std_r:.5f} Sharpe={sr:.3f}")

fig4_df = pd.DataFrame(records)
fig4_df.to_csv(f"{OUT}/fig4_asset_count.csv", index=False)
display(fig4_df.pivot(index="Model", columns="i", values="sharpe"))

[asset-count] RF        i= 6  mean=+0.01152 std=0.05354 Sharpe=0.215

[asset-count] RF        i= 7  mean=+0.01257 std=0.05155 Sharpe=0.244

[asset-count] RF        i= 8  mean=+0.01198 std=0.05178 Sharpe=0.231

[asset-count] RF        i= 9  mean=+0.01218 std=0.05138 Sharpe=0.237

[asset-count] RF        i=10  mean=+0.01216 std=0.05104 Sharpe=0.238

[asset-count] AdaBoost  i= 6  mean=+0.01355 std=0.05790 Sharpe=0.234

[asset-count] AdaBoost  i= 7  mean=+0.01355 std=0.05753 Sharpe=0.235

[asset-count] AdaBoost  i= 8  mean=+0.01330 std=0.05762 Sharpe=0.231

[asset-count] AdaBoost  i= 9  mean=+0.01301 std=0.05802 Sharpe=0.224

[asset-count] AdaBoost  i=10  mean=+0.01377 std=0.05799 Sharpe=0.237

[asset-count] XGBoost   i= 6  mean=+0.01543 std=0.05207 Sharpe=0.296

[asset-count] XGBoost   i= 7  mean=+0.01306 std=0.04497 Sharpe=0.290

[asset-count] XGBoost   i= 8  mean=+0.01343 std=0.04306 Sharpe=0.312

[asset-count] XGBoost   i= 9  mean=+0.01272 std=0.04339 Sharpe=0.293

[asset-count] XGBoost   i=10  mean=+0.01325 std=0.04244 Sharpe=0.312

[asset-count] SVR       i= 6  mean=+0.01284 std=0.08639 Sharpe=0.149

[asset-count] SVR       i= 7  mean=+0.00814 std=0.08392 Sharpe=0.097

[asset-count] SVR       i= 8  mean=+0.01244 std=0.08030 Sharpe=0.155

[asset-count] SVR       i= 9  mean=+0.00520 std=0.07135 Sharpe=0.073

[asset-count] SVR       i=10  mean=+0.00489 std=0.07150 Sharpe=0.068

[asset-count] KNN       i= 6  mean=+0.01623 std=0.06226 Sharpe=0.261

[asset-count] KNN       i= 7  mean=+0.01541 std=0.05587 Sharpe=0.276

[asset-count] KNN       i= 8  mean=+0.01520 std=0.05645 Sharpe=0.269

[asset-count] KNN       i= 9  mean=+0.01598 std=0.05679 Sharpe=0.281

[asset-count] KNN       i=10  mean=+0.01548 std=0.05760 Sharpe=0.269

[asset-count] RNN       i= 6  mean=+0.01437 std=0.08028 Sharpe=0.179

[asset-count] RNN       i= 7  mean=+0.01038 std=0.07031 Sharpe=0.148

[asset-count] RNN       i= 8  mean=+0.01161 std=0.07018 Sharpe=0.165

[asset-count] RNN       i= 9  mean=+0.01051 std=0.06722 Sharpe=0.156

[asset-count] RNN       i=10  mean=+0.01081 std=0.06636 Sharpe=0.163

i               6         7         8         9         10
Model
AdaBoost  0.234047  0.235451  0.230815  0.224277  0.237486
KNN       0.260635  0.275764  0.269218  0.281408  0.268679
RF        0.215250  0.243731  0.231399  0.236988  0.238214
RNN       0.178966  0.147576  0.165415  0.156375  0.162861
SVR       0.148659  0.096990  0.154917  0.072837  0.068414
XGBoost   0.296369  0.290415  0.311953  0.293169  0.312198

In [15]:

fig, axes = plt.subplots(3, 1, figsize=(8, 11))
metric_cols = [("mean_return", "Mean Return"), ("std_return", "Standard Deviation"),
               ("sharpe", "Sharpe Ratio")]
width = 0.13
x_pos = np.arange(len(ASSET_COUNTS))
for ax, (col, title) in zip(axes, metric_cols):
    for j, model_name in enumerate(MODELS):
        sub = fig4_df[fig4_df["Model"] == model_name].set_index("i").loc[ASSET_COUNTS, col]
        ax.bar(x_pos + j * width, sub.values, width=width, label=model_name)
    ax.set_xticks(x_pos + width * (len(MODELS) - 1) / 2)
    ax.set_xticklabels([f"i = {i}" for i in ASSET_COUNTS])
    ax.set_title(title)
    ax.legend(fontsize=7, ncol=3)
plt.tight_layout()
plt.savefig(f"{OUT}/fig4_asset_count_performance.png", dpi=150)
plt.show()
print(f"saved {OUT}/fig4_asset_count_performance.png")

saved outputs/fig4_asset_count_performance.png

In [16]:

weight_tables = {}
for lam in LAMBDAS:
    rows_w, f_row, r_row = {}, {}, {}
    for model_name in MODELS:
        pool = load_pool(model_name).head(10)
        companies = pool["Company"].tolist()
        mu = pool["pred_return"].values
        sigma, sub = sigma_for(companies, wide)

        x_mean, r_mean, f_mean, xs, rs, fs = run_sa_multi(
            mu, sigma, lam=lam, alpha=ALPHA, n_runs=N_SA_RUNS, seed0=1000)

        rows_w[f"{model_name}+EN-MVP"] = x_mean
        f_row[f"{model_name}+EN-MVP"] = f_mean
        r_row[f"{model_name}+EN-MVP"] = r_mean
        print(f"[risk-regime lam={lam}] {model_name:9s} r*={r_mean:.4f} F={f_mean:.5f} "
              f"nonzero={np.sum(x_mean > 0)}")

    table = pd.DataFrame(rows_w, index=[f"Stock {k+1}" for k in range(10)])
    table.loc["F"] = f_row
    table.loc["r*"] = r_row
    weight_tables[lam] = table
    fname = f"{OUT}/{'table5' if lam == 0.01 else 'table6'}_allocation_lambda{lam}.csv"
    table.to_csv(fname)

display(weight_tables[0.01])

[risk-regime lam=0.01] RF        r*=0.3901 F=-0.01526 nonzero=10

[risk-regime lam=0.01] AdaBoost  r*=0.4084 F=-0.03634 nonzero=9

[risk-regime lam=0.01] XGBoost   r*=0.0000 F=0.00581 nonzero=10

[risk-regime lam=0.01] SVR       r*=0.4118 F=-0.04089 nonzero=9

[risk-regime lam=0.01] KNN       r*=0.4739 F=-0.10991 nonzero=8

[risk-regime lam=0.01] RNN       r*=0.3496 F=-0.06716 nonzero=10

[risk-regime lam=0.99] RF        r*=0.0023 F=0.00268 nonzero=9

[risk-regime lam=0.99] AdaBoost  r*=0.0456 F=0.00360 nonzero=10

[risk-regime lam=0.99] XGBoost   r*=0.0255 F=0.00205 nonzero=9

[risk-regime lam=0.99] SVR       r*=0.0430 F=0.00505 nonzero=9

[risk-regime lam=0.99] KNN       r*=0.0375 F=0.00287 nonzero=10

[risk-regime lam=0.99] RNN       r*=0.0408 F=0.00415 nonzero=9

,RF+EN-MVP,AdaBoost+EN-MVP,XGBoost+EN-MVP,SVR+EN-MVP,KNN+EN-MVP,RNN+EN-MVP
Stock 1,0.834728,0.523341,0.110683,0.813602,0.852073,0.816546
Stock 2,0.019530,0.433425,0.098985,0.052055,0.048870,0.069193
Stock 3,0.047920,0.010129,0.073463,0.061258,0.016324,0.048842
Stock 4,0.024575,0.005748,0.075594,0.045054,0.014523,0.031821
Stock 5,0.003753,0.006242,0.101415,0.011405,0.009893,0.004846
Stock 6,0.029648,0.006637,0.112095,0.004253,0.031795,0.005151
Stock 7,0.009609,0.000000,0.132151,0.005392,0.009789,0.006634
Stock 8,0.012902,0.007046,0.107813,0.001628,0.000000,0.008573
Stock 9,0.012199,0.003825,0.099807,0.000000,0.000000,0.006311
Stock 10,0.005136,0.003609,0.087996,0.005352,0.016733,0.002083
F,-0.015255,-0.036344,0.005808,-0.040891,-0.109908,-0.067158
r*,0.390056,0.408427,0.000000,0.411842,0.473929,0.349619

In [17]:

display(weight_tables[0.99])

,RF+EN-MVP,AdaBoost+EN-MVP,XGBoost+EN-MVP,SVR+EN-MVP,KNN+EN-MVP,RNN+EN-MVP
Stock 1,0.099146,0.001127,0.243340,0.064296,0.012138,0.046206
Stock 2,0.027415,0.010734,0.016010,0.092357,0.064099,0.000000
Stock 3,0.330644,0.018035,0.007297,0.129699,0.001673,0.008914
Stock 4,0.003795,0.279363,0.001034,0.004131,0.150828,0.194728
Stock 5,0.051397,0.266571,0.000000,0.041956,0.002701,0.010443
Stock 6,0.142358,0.327069,0.128469,0.021267,0.284575,0.065263
Stock 7,0.195260,0.036260,0.256120,0.133931,0.396384,0.315299
Stock 8,0.000000,0.008366,0.249426,0.116837,0.024600,0.003903
Stock 9,0.054686,0.047835,0.093422,0.395526,0.041162,0.349243
Stock 10,0.095299,0.004640,0.004883,0.000000,0.021840,0.006001
F,0.002679,0.003602,0.002046,0.005052,0.002873,0.004152
r*,0.002326,0.045563,0.025480,0.042995,0.037481,0.040819

In [18]:

# One fixed, high-contrast colour per model, shared between a model's EN-MVP
# line and its 1/N benchmark line (distinguished instead by linestyle/marker)
# and reused identically across both risk-regime figures. This replaces the
# default 10-colour matplotlib cycle running unrelated across all 12 lines,
# which made the EN-MVP/1-N pairing for a given model hard to trace.
MODEL_COLORS = dict(zip(MODELS, plt.get_cmap("tab10").colors[:6]))
MODEL_MARKERS = dict(zip(MODELS, ["o", "s", "^", "D", "v", "P"]))

for lam in LAMBDAS:
    table = weight_tables[lam]
    fig, ax = plt.subplots(figsize=(11, 7))
    dates = None
    for model_name in MODELS:
        pool = load_pool(model_name).head(10)
        companies = pool["Company"].tolist()
        sub = wide[companies]
        weights = table[f"{model_name}+EN-MVP"].iloc[:10].values.astype(float)

        en_series = portfolio_series(weights, sub)
        ew_series = portfolio_series(equal_weight(len(companies)), sub)

        en_cum = cumulative_return(en_series)
        ew_cum = cumulative_return(ew_series)
        if dates is None:
            dates = sub.index.values

        color = MODEL_COLORS[model_name]
        marker = MODEL_MARKERS[model_name]
        ax.plot(dates, en_cum, color=color, linestyle="-", linewidth=2.0,
                 marker=marker, markersize=4, markevery=5,
                 label=f"{model_name}+EN-MVP")
        ax.plot(dates, ew_cum, color=color, linestyle="--", linewidth=1.3,
                 alpha=0.65, label=f"{model_name}+1/N")

    ax.set_xlabel("Month index (0 = Jan 2018)")
    ax.set_ylabel("Cumulative Return")
    ax.set_title(f"Cumulative return, lambda={lam} "
                 f"(solid+markers = EN-MVP, dashed = 1/N benchmark; "
                 f"colour identifies the prediction model)")
    ax.axhline(0, color="black", linewidth=0.6, alpha=0.5, zorder=0)
    ax.grid(alpha=0.25, linewidth=0.5)
    ax.legend(fontsize=8, ncol=2, loc="upper left", framealpha=0.9)
    plt.tight_layout()
    fname = f"{OUT}/fig{'5' if lam == 0.01 else '6'}_cumret_lambda{lam}.png"
    plt.savefig(fname, dpi=150)
    plt.show()
    print(f"[cumret] saved {fname}")

[cumret] saved outputs/fig5_cumret_lambda0.01.png

[cumret] saved outputs/fig6_cumret_lambda0.99.png


## 9. Results summary

Headline, honest findings from this pipeline (genuine properties of the
data/model combination, not adjustable by re-running):

1. **The originally-borrowed `alpha=0.06`** (Yen & Yen, 2014, a different
   dataset) dominates Eq. (11)'s risk-return trade-off terms at this
   sample's scale: SA converges to `r* ~= 0` in every regime, so no weight is
   ever driven below the sparsity threshold. Section 7's validation grid
   search recalibrates it to `alpha=0.001`, which keeps `r*` away from its
   degenerate value (mean `r*=0.262` across the 12 model/regime
   combinations) and restores genuine, if modest, sparsity.
2. **XGBoost's Table-1 hyperparameters (`learning_rate=0.01`, `gamma=2`)
   collapse its forward predictions to an almost-constant value** on this
   feature set (Section 4 sanity check) -- `gamma=2` is high relative to the
   achievable gain on noisy monthly-return data with only 7 features, so
   almost no tree in the ensemble ever splits.
3. At the calibrated alpha, **XGBoost+EN-MVP gives the highest Sharpe ratio
   at every portfolio size tested**, while **KNN+EN-MVP gives the highest
   mean return**; EN-MVP portfolios outperform the equal-weight (1/N)
   benchmark in only 3 of the 12 predictor/regime combinations tested
   (Section 8).
4. The calibrated `r*` is roughly an order of magnitude larger under the
   return-seeking regime ($\lambda=0.01$) than the risk-averse regime
   ($\lambda=0.99$) for five of six predictors: return-seeking objectives
   favour sparse allocations, risk-averse objectives favour shrinkage.

See `main.tex` (Sections 5-7) for the full discussion, and `README.md` for
the complete list of documented modelling assumptions and deviations from
the manuscript's Table 1 hyperparameters.